name: github pages

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: false  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          #hugo-version: 'latest'
<<<<<<< HEAD
          hugo-version:0.92.2
=======
          hugo-version: 0.92.2
>>>>>>> c6a7898240fd4bcc81277e85adc7decbb838b3b9
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          # github_token: ${{ secrets.GITHUB_TOKEN }}
          github_token: ${{ secrets.GH_PAGES_DEPLOY }}
          publish_dir: ./public
